// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQRLDotNetClientUI.DB.DBContext;

namespace SQRLDotNetClientUI.Migrations
{
    [DbContext(typeof(SQRLDBContext))]
    [Migration("20200219133551_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("SQRLDotNetClientUI.DB.Models.Identity", b =>
                {
                    b.Property<string>("UniqueId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("DataBytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("GenesisId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("UniqueId");

                    b.ToTable("Identities");
                });

            modelBuilder.Entity("SQRLDotNetClientUI.DB.Models.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastLoadedIdentity")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserData");
                });
#pragma warning restore 612, 618
        }
    }
}
